server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:33306/software?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host:
    port:
    password: 

mybatis-plus:
  global-config:
    db-config:
      # 启用主键自增
      id-type: auto

register:
  ip: 
  port: 
